name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-tags: true

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install twine wheel

    - name: Build
      run: |
        python setup.py sdist bdist_wheel
        version=$(python setup.py --version)
        echo "::set-output name=archive::"openttd-helpers-${version}.tar.gz""
        echo "::set-output name=wheel::"openttd_helpers-${version}-py3-none-any.whl""
      id: build

    - name: Publish to PyPi
      env:
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        twine upload --username __token__ dist/*.whl dist/*.tar.gz

    - name: Publish Source to GitHub releases
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: ./dist/${{ steps.build.outputs.archive }}

    - name: Publish Wheel to GitHub releases
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: ./dist/${{ steps.build.outputs.wheel }}
