name: Testing

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  codeql:
    name: Security and Quality
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        # Must fetch at least the immediate parents so that if this is
        # a pull request then we can checkout the head of the pull request.
        fetch-depth: 2
    # If this run was triggered by a pull request event then checkout
    # the head of the pull request instead of the merge commit.
    - run: git checkout HEAD^2
      if: ${{ github.event_name == 'pull_request' }}
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: python -m pip install -e .
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: python
        queries: security-and-quality
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1

  flake8:
    name: Flake8
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Flake8
      uses: TrueBrain/actions-flake8@master
      with:
        path: examples openttd_helpers regression_runner

  black:
    name: Black
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Black
      run: |
        python -m pip install --upgrade pip
        pip install black
        black -l 120 --check examples openttd_helpers regression_runner

  regression:
    name: Regression
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Set up packages
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install -r regression_runner/requirements.txt
    - name: Regression
      run: |
        make regression
